"""Add status column to booking

Revision ID: 18efeb258e17
Revises: 
Create Date: 2025-09-21 06:26:23.472848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18efeb258e17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
