"""Initial migration

Revision ID: d806bd859e10
Revises: b707f43040f5
Create Date: 2025-10-04 15:19:58.084206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd806bd859e10'
down_revision = 'b707f43040f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
